### ISSUE TITLE
Remove ZF3 deprecation notice

### ISSUE THREAD

**Issue by oursgris** [gkralik/gk-smarty#10]
Hello
when I run that code on my dev server with ZF2
I have :
`Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your GkSmarty\View\HelperPluginManager plugin manager factory to inject the parent service locator via the constructor. in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\ges2\ges2\vendor\zendframework\zend-mvc\src\Service\ServiceManagerConfig.php on line 175`

I remove that warning using http://stackoverflow.com/questions/35807588/zf2-servicelocatorawareinterface-is-deprecated-and-will-be-removed-in-version

**Comment by gkralik** [comment]
Thanks for reporting this. It should not affect the functionality and I will have a look over the next week to refactor this.

**Comment by oursgris** [comment]
Oh thank you, it's very fast

**Comment by oursgris** [comment]
Btw if you can have a parameter for SmartyBC it would help the migration (I'm migrating ZF1 to ZF2 and I've some {php} which don't exist on Smarty)

**Comment by gkralik** [comment]
I'll have a look, but it'll take a few days.

**Comment by oursgris** [comment]
i'm sorry to bother you but I'm a bit lost
Can I ask you some questions ? If not please tell me and I'll stop it

i'm migrating ZF1 to ZF2 as I told you

I didn't manage to recover my good old views
in module.config.php

I put the following conf (and gk_smarty conf also)
> 'view_manager' => array(
>         'strategies' => array(
>             'GkSmartyStrategy'
>         ),
>         'template_map' => array(
>             'layout/layout' => __DIR__ . '/../view/actor/login.tpl',
>             'application/index/index' => __DIR__ . '/../view/application/index/index.tpl',
>             'error/404' => __DIR__ . '/../view/error/404.tpl',
>             'error' => __DIR__ . '/../view/error/index.tpl',
>             'actor/index' => __DIR__ . '/../view/actor/index.tpl',
>             'actor/login' => __DIR__ . '/../view/actor/login.tpl'
>         )
>     )

when I access with the ActorController / LoginAction
it allways returns me the layout/layout view
and not the actor/login

btw I tryied that : 

        $view = new ViewModel();
        $view->setTemplate('actor/login');
        return $view;

it doesn't work alors ..
can you help me to resolve that issue ?

best regards

**Comment by oursgris** [comment]
oh my dear I'm sorry
I had to use $this->layout

**Comment by gkralik** [comment]
Which version of ZF are you using?

**Comment by oursgris** [comment]
the last, ZF 2.5 it's hard i had a lot of problem (it's normal I fear with the age of ZF1)
at this time I use that the following code to migrate my form 
        
        $this->layout('questionnaire/index');
        $params = array('v' => $this->view); 
        $this->layout()->setVariables(array(
            'v' => $this->view,
        ));
        $view = new ViewModel($params);
        return $view;

but I've a big problem with that error 
Fatal error: Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDO instances' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\ges2\ges2\vendor\zendframework\zend-stdlib\src\PriorityQueue.php on line 178

it's very strange, because I put only array objects into the ViewModel :(

**Comment by oursgris** [comment]
that small peace of code in a action hang with that error : 
        $test[] = 1;
        $enquetes[] = $test;
        $this->layout('questionnaire/index');
        $this->layout()->setVariables(array(
            'enquetes' => $enquetes,
        ));
        $view = new ViewModel();
        return $view;

and in the tpl : 

  {foreach $enquetes as $enquete}
  	<tr>
	</tr>
  {/foreach}

**Comment by gkralik** [comment]
I updated the module. In version 1.1.0 the deprecation notice is removed.
Also there is the new option `use_smarty_bc` to use the SmartyBC implementation instead of the default one. See [the changes](https://github.com/gkralik/gk-smarty/compare/1.0.0...1.1.0)
